Added additional step to run unit tests before release

diff --git a/.github/workflows/rel-build.yaml b/.github/workflows/rel-build.yaml
--- a/.github/workflows/rel-build.yaml
+++ b/.github/workflows/rel-build.yaml
@@ -57,9 +57,28 @@ jobs:
       - name: Clean up Docker image
         run: |
           docker system prune -f || true
-  release:
+  test:
     runs-on: ubuntu-latest
     needs: build
+    steps:
+      - name: Download artifact from build job
+        uses: actions/download-artifact@v4
+        with:
+          name: rel-build-v${{ needs.build.outputs.VERSION }}
+          path: artifacts/
+      - name: Run tests
+        run: |
+          tar -xzf artifacts/test_calculator_${{ needs.build.outputs.VERSION }}.tar.gz -C artifacts/
+          if [ -f artifacts/test_calculator ]; then
+            echo "Running tests..."
+            ./artifacts/test_calculator
+          else
+            echo "Test binary not found!"
+            exit 1
+          fi
+  release:
+    runs-on: ubuntu-latest
+    needs: test
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
@@ -72,4 +91,6 @@ jobs:
           tag_name: ${{ github.ref_name }}
           name: Release ${{ github.ref_name }}
           generate_release_notes: true
-          files: artifacts/*
+          files: |
+            artifacts/calculator*.tar.gz
+            artifacts/calculator*.deb
